/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "d_ff.v:1.1-12.10" *)
module d_ff(clk, rst, d, q);
  (* src = "d_ff.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "d_ff.v:2.13-2.16" *)
  input rst;
  wire rst;
  (* src = "d_ff.v:2.17-2.18" *)
  input d;
  wire d;
  (* src = "d_ff.v:3.13-3.14" *)
  output q;
  wire q;
  wire _0_;
  wire _1_;
  INVX1 _2_ (
    .A(d),
    .Y(_1_)
  );
  NOR2X1 _3_ (
    .A(_1_),
    .B(rst),
    .Y(_0_)
  );
  (* src = "d_ff.v:6.1-11.4" *)
  DFFPOSX1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule
