/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "decoder1.v:1.1-11.10" *)
module decoder1(en, a, y);
  (* src = "decoder1.v:2.8-2.10" *)
  input en;
  wire en;
  (* src = "decoder1.v:3.14-3.15" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "decoder1.v:4.15-4.16" *)
  output [3:0] y;
  wire [3:0] y;
  (* src = "decoder1.v:10.15-10.24" *)
  wire _00_;
  (* src = "decoder1.v:7.15-7.25" *)
  wire _01_;
  (* src = "decoder1.v:7.20-7.25" *)
  wire _02_;
  (* src = "decoder1.v:7.28-7.33" *)
  wire _03_;
  assign y[0] = _01_ &(* src = "decoder1.v:7.15-7.33" *)  _03_;
  assign _01_ = en &(* src = "decoder1.v:8.15-8.25" *)  _02_;
  assign y[1] = _01_ &(* src = "decoder1.v:8.15-8.32" *)  a[0];
  assign y[2] = _00_ &(* src = "decoder1.v:9.15-9.32" *)  _03_;
  assign _00_ = en &(* src = "decoder1.v:10.15-10.24" *)  a[1];
  assign y[3] = _00_ &(* src = "decoder1.v:10.15-10.31" *)  a[0];
  assign _02_ = ~(* src = "decoder1.v:8.20-8.25" *) a[1];
  assign _03_ = ~(* src = "decoder1.v:9.27-9.32" *) a[0];
endmodule
