/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "shift_reg.v:1.1-14.10" *)
module shift_reg(clk, rst, data_in, q);
  (* src = "shift_reg.v:2.13-2.16" *)
  input clk;
  wire clk;
  (* src = "shift_reg.v:2.18-2.21" *)
  input rst;
  wire rst;
  (* src = "shift_reg.v:3.19-3.26" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "shift_reg.v:4.19-4.20" *)
  output [7:0] q;
  reg [7:0] q;
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[0] <= 1'h0;
    else q[0] <= data_in[7];
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[1] <= 1'h0;
    else q[1] <= q[0];
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[2] <= 1'h0;
    else q[2] <= q[1];
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[3] <= 1'h0;
    else q[3] <= q[2];
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[4] <= 1'h0;
    else q[4] <= q[3];
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[5] <= 1'h0;
    else q[5] <= q[4];
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[6] <= 1'h0;
    else q[6] <= q[5];
  (* src = "shift_reg.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q[7] <= 1'h0;
    else q[7] <= q[6];
endmodule
