/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:1.1-12.10" *)
module counter(clk, reset, count);
  (* src = "counter.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "counter.v:2.13-2.18" *)
  input reset;
  wire reset;
  (* src = "counter.v:3.19-3.24" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.12-10.21|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:10.12-10.21|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _07_;
  INVX1 _08_ (
    .A(count[0]),
    .Y(_06_[0])
  );
  INVX1 _09_ (
    .A(reset),
    .Y(_00_)
  );
  NAND2X1 _10_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_04_)
  );
  NAND3X1 _11_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .Y(_05_)
  );
  XNOR2X1 _12_ (
    .A(count[3]),
    .B(_05_),
    .Y(_07_[3])
  );
  XNOR2X1 _13_ (
    .A(count[2]),
    .B(_04_),
    .Y(_07_[2])
  );
  XOR2X1 _14_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_07_[1])
  );
  INVX1 _15_ (
    .A(reset),
    .Y(_01_)
  );
  INVX1 _16_ (
    .A(reset),
    .Y(_02_)
  );
  INVX1 _17_ (
    .A(reset),
    .Y(_03_)
  );
  (* src = "counter.v:6.1-11.4" *)
  DFFSR _18_ (
    .CLK(clk),
    .D(_06_[0]),
    .Q(count[0]),
    .R(_02_),
    .S(1'h1)
  );
  (* src = "counter.v:6.1-11.4" *)
  DFFSR _19_ (
    .CLK(clk),
    .D(_07_[1]),
    .Q(count[1]),
    .R(_01_),
    .S(1'h1)
  );
  (* src = "counter.v:6.1-11.4" *)
  DFFSR _20_ (
    .CLK(clk),
    .D(_07_[2]),
    .Q(count[2]),
    .R(_00_),
    .S(1'h1)
  );
  (* src = "counter.v:6.1-11.4" *)
  DFFSR _21_ (
    .CLK(clk),
    .D(_07_[3]),
    .Q(count[3]),
    .R(_03_),
    .S(1'h1)
  );
  assign { _07_[31:5], _07_[0] } = { 27'h0000000, _06_[0] };
  assign _06_[31:1] = { 28'h0000000, count[3:1] };
endmodule
